name: workflow yaml 
on: 
  push: 
    branches: 
      - feature 
      - develop
  workflow_dispatch: 

jobs: 
  get-version: 
    runs-on: ubuntu-latest
    outputs: 
      value1: ${{steps.version.outputs.VERSION}}
      value2: ${{steps.version.outputs.VERSION1}}
    steps: 
    - name: checkout code 
      uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - name: run get version
      id: version
      run: |
        version=$(git describe --tags | cut -d '-' -f 1)
        version1=$(git describe --tags | cut -d '-' -f 2)
        echo "::set-output name=VERSION::$version"
        echo "::set-output name=VERSION1::$version1"
      
  maven-build: 
    needs: get-version
    runs-on: ubuntu-latest
    steps: 
    - name: run maven build 
      run: |
        echo "maven build and then archive"
        echo "Is this printing version ${{needs.get-version.outputs.value1}}"
        echo "Is this printing version1 ${{needs.get-version.outputs.value2}}"
  docker-build: 
    needs: get-version
    runs-on: ubuntu-latest
    steps:
    - name: run docker build 
      run: echo "Run docker build and push"
  deploy-dev: 
    needs: docker-build
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
    environment: dev
    steps: 
    - name: Test in two steps below 
      run: |
        echo "maven build and then archive"
        echo "Is this printing ${{needs.docker-build.get-version.outputs.version}}"

  deploy-uat: 
    needs: docker-build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    environment: uat 
    steps: 
    - name: run uat update yaml 
      run: echo "update uat yaml kustomize"
  create-release: 
    needs: docker-build 
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: prod
    steps: 
    - name: run the release 
      run: echo "createing release"

  deploy-prod: 
    needs: create-release
    runs-on: ubuntu-latest
    environment: prod 
    steps: 
    - name: update prod 
      run: echo "update prod yaml"
# test comment 
  

  